# Format checks enforced on CI:
# 1. Comments must appear above each field.
# 2. There must be a blank line between each field.
# 3. Inline comments (after a field on the same line) are not allowed.
# 4. Indentation level is respected for nested fields.

# defaults specify the default config from each component
defaults:
  # dp actor config, inheriting from trainer/config/teacher_model/teacher_model.yaml
  - teacher_model

  # fsdp engine config
  - ../engine@fsdp_config: fsdp

  # load the reference default config, then apply the fields in the current yaml
  - _self_

model: null

# sequence parallel size
ulysses_sequence_parallel_size: 1

# calculate entropy with chunking to reduce memory peak
entropy_from_logits_with_chunking: False

# recompute entropy
entropy_checkpointing: False
